import { 
  Member, Department, ChurchEvent, AttendanceRecord, 
  Devotional, Sermon, DocumentItem, GalleryItem, Announcement, 
  PrayerRequest, PastoralFollowUp, WhatsAppConfig, WhatsAppTemplate, 
  WhatsAppMessage, WhatsAppCampaign, ChurchSettings, AuditLog, BibleVerseItem, ReadingPlan, ChurchTenant 
} from './types';

export const INITIAL_TENANTS: ChurchTenant[] = [
  {
    id: 'tenant-1',
    slug: 'the-church',
    name: 'The Church',
    slogan: 'Connecting the Church. Caring for People. Growing Together.',
    logoUrl: '/church-logo.jpg',
    address: '45 Kingdom Way, Sanctuary Heights, London / Lagos',
    phone: '+1 (555) 728-4673',
    email: 'pastor@thechurch.org',
    website: 'https://thechurch.org',
    pastorName: 'Pastor David Adeleke',
    pastorEmail: 'david.adeleke@thechurch.org',
    primaryColor: '#0a3678', // Deep Royal Navy Blue from Logo
    secondaryColor: '#df991d', // Warm Golden Amber from Logo
    status: 'active',
    plan: 'enterprise',
    createdAt: '2025-01-10',
    memberCount: 1248,
    adminEmail: 'pastor@thechurch.org',
  },
  {
    id: 'tenant-2',
    slug: 'grace-chapel',
    name: 'Grace Chapel International',
    slogan: 'Grace for Living. Hope for Generations.',
    logoUrl: 'https://images.unsplash.com/photo-1548625361-177bfb30d3db?auto=format&fit=crop&w=200&q=80',
    address: '120 Bishopsgate, London EC2N 4DQ',
    phone: '+44 20 7946 0192',
    email: 'contact@gracechapel.org',
    website: 'https://gracechapel.org',
    pastorName: 'Pastor Emmanuel Mensah',
    pastorEmail: 'pastor@gracechapel.org',
    primaryColor: '#059669', // Emerald Green
    secondaryColor: '#10b981',
    status: 'active',
    plan: 'growth',
    createdAt: '2025-06-20',
    memberCount: 650,
    adminEmail: 'pastor@gracechapel.org',
  },
  {
    id: 'tenant-3',
    slug: 'living-word',
    name: 'Living Word Cathedral',
    slogan: 'Transforming Lives Through the Word of Faith.',
    logoUrl: 'https://images.unsplash.com/photo-1438232992991-995b7058bbb3?auto=format&fit=crop&w=200&q=80',
    address: '440 Peachtree St NE, Atlanta, GA 30308',
    phone: '+1 (404) 555-0188',
    email: 'office@livingword.org',
    website: 'https://livingwordcathedral.org',
    pastorName: 'Bishop Marcus Johnson',
    pastorEmail: 'bishop@livingword.org',
    primaryColor: '#7c3aed', // Royal Purple
    secondaryColor: '#f59e0b',
    status: 'active',
    plan: 'growth',
    createdAt: '2025-09-15',
    memberCount: 890,
    adminEmail: 'bishop@livingword.org',
  },
];

export const INITIAL_SETTINGS: ChurchSettings = {
  churchName: 'The Church',
  slogan: 'Connecting the Church. Caring for People. Growing Together.',
  logoUrl: '/church-logo.jpg',
  address: '45 Kingdom Way, Sanctuary Heights, London / Lagos',
  phone: '+1 (555) 728-4673',
  email: 'pastor@thechurch.org',
  website: 'https://thechurch.org',
  pastorName: 'Pastor David Adeleke',
  pastorEmail: 'david.adeleke@thechurch.org',
  primaryColor: '#0a3678', // Deep Royal Navy Blue from Logo
  secondaryColor: '#df991d', // Warm Golden Amber from Logo
  socialLinks: {
    facebook: 'https://facebook.com',
    youtube: 'https://youtube.com',
    instagram: 'https://instagram.com',
    twitter: 'https://x.com',
  },
  serviceTimes: [
    { day: 'Sunday', name: 'Celebration Worship Service', time: '09:00 AM & 11:15 AM' },
    { day: 'Wednesday', name: 'Midweek Bible Study & Communion', time: '06:30 PM' },
    { day: 'Friday', name: 'Hour of Power & Prayer Vigil', time: '07:00 PM' },
  ],
  setupCompleted: true,
};

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-1',
    name: 'Sanctuary Choir',
    description: 'Leading the congregation into deep, spirit-filled praise and worship.',
    leaderId: 'mem-3',
    leaderName: 'Grace Okafor',
    assistantLeaderName: 'Joshua Mensah',
    memberCount: 28,
    meetingDay: 'Thursday',
    meetingTime: '06:00 PM',
    color: '#0284c7',
  },
  {
    id: 'dept-2',
    name: 'Ushering & Protocol',
    description: 'Welcoming members and visitors with Christ-like warmth and maintaining church order.',
    leaderId: 'mem-5',
    leaderName: 'Michael Sterling',
    assistantLeaderName: 'Deborah Vance',
    memberCount: 22,
    meetingDay: 'Saturday',
    meetingTime: '09:00 AM',
    color: '#0d9488',
  },
  {
    id: 'dept-3',
    name: 'Youth & Young Adults (Ignite)',
    description: 'Empowering the next generation through relevant discipleship and fellowship.',
    leaderId: 'mem-4',
    leaderName: 'Emmanuel Cole',
    assistantLeaderName: 'Ruth Adams',
    memberCount: 65,
    meetingDay: 'Saturday',
    meetingTime: '04:00 PM',
    color: '#e11d48',
  },
  {
    id: 'dept-4',
    name: 'Media & Communications',
    description: 'Broadcasting Sunday livestreams, sound engineering, visuals and social engagement.',
    leaderId: 'mem-2',
    leaderName: 'Sarah Jenkins',
    assistantLeaderName: 'Daniel Obi',
    memberCount: 16,
    meetingDay: 'Wednesday',
    meetingTime: '05:30 PM',
    color: '#7c3aed',
  },
  {
    id: 'dept-5',
    name: 'Intercessory Prayer Team',
    description: 'Standing in the gap for the church, pastors, members, and the community.',
    leaderId: 'mem-8',
    leaderName: 'Mother Abigail Adebayo',
    assistantLeaderName: 'Elder Samuel Vance',
    memberCount: 30,
    meetingDay: 'Tuesday',
    meetingTime: '06:00 PM',
    color: '#b45309',
  },
  {
    id: 'dept-6',
    name: 'Welfare & Hospitality',
    description: 'Caring for widows, orphans, sick brethren, and providing food packages.',
    leaderId: 'mem-7',
    leaderName: 'Beatrice Wilson',
    assistantLeaderName: 'Esther Davies',
    memberCount: 18,
    meetingDay: 'First Saturday',
    meetingTime: '10:00 AM',
    color: '#059669',
  },
];

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'mem-1',
    fullName: 'David Adeleke',
    firstName: 'David',
    lastName: 'Adeleke',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    gender: 'male',
    dateOfBirth: '1982-10-04', // Birthday TODAY (Oct 4)!
    phoneNumber: '+1-555-0101',
    whatsAppNumber: '+15550101',
    email: 'david.adeleke@thechurch.org',
    residentialAddress: '12 Grace Avenue, City Center',
    occupation: 'Lead Pastor & Author',
    maritalStatus: 'married',
    weddingAnniversary: '2008-08-16',
    dateJoined: '2015-01-10',
    baptismStatus: 'baptized',
    departmentId: 'dept-5',
    departmentName: 'Pastoral Council',
    ministry: 'Preaching & Pastoral Care',
    cellGroup: 'Sanctuary Cell',
    emergencyContact: { name: 'Mary Adeleke', relationship: 'Spouse', phone: '+1-555-0102' },
    memberStatus: 'worker',
    notes: 'Senior Pastor. Founded local outreach in 2018.',
    privacy: { showPhone: true, showEmail: true, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2015-01-10', baptizedDate: '2000-04-12', completedDiscipleship: true, workerOrdainedDate: '2005-09-20' },
  },
  {
    id: 'mem-2',
    fullName: 'Sarah Jenkins',
    firstName: 'Sarah',
    lastName: 'Jenkins',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    gender: 'female',
    dateOfBirth: '1994-10-04', // Birthday TODAY (Oct 4)!
    phoneNumber: '+1-555-0103',
    whatsAppNumber: '+15550103',
    email: 'sarah.jenkins@example.com',
    residentialAddress: '88 Meadow Lane, Brookside',
    occupation: 'Creative Director',
    maritalStatus: 'single',
    dateJoined: '2021-03-14',
    baptismStatus: 'baptized',
    departmentId: 'dept-4',
    departmentName: 'Media & Communications',
    ministry: 'Livestream & Graphic Design',
    cellGroup: 'Young Professionals Cell',
    emergencyContact: { name: 'Robert Jenkins', relationship: 'Father', phone: '+1-555-0104' },
    memberStatus: 'worker',
    notes: 'Heads video production and weekly broadcast.',
    privacy: { showPhone: true, showEmail: true, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2021-03-14', baptizedDate: '2021-06-20', departmentJoinedDate: '2021-08-01', completedDiscipleship: true },
  },
  {
    id: 'mem-3',
    fullName: 'Grace Okafor',
    firstName: 'Grace',
    lastName: 'Okafor',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    gender: 'female',
    dateOfBirth: '1990-10-04', // Birthday TODAY (Oct 4)!
    phoneNumber: '+1-555-0105',
    whatsAppNumber: '+15550105',
    email: 'grace.okafor@example.com',
    residentialAddress: '24 Harmony Close, West End',
    occupation: 'Music Educator',
    maritalStatus: 'married',
    weddingAnniversary: '2016-11-22',
    dateJoined: '2018-09-02',
    baptismStatus: 'baptized',
    departmentId: 'dept-1',
    departmentName: 'Sanctuary Choir',
    cellGroup: 'Harmony Fellowship',
    emergencyContact: { name: 'Chidi Okafor', relationship: 'Husband', phone: '+1-555-0106' },
    memberStatus: 'worker',
    notes: 'Worship leader and choir director.',
    privacy: { showPhone: true, showEmail: false, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2018-09-02', baptizedDate: '2010-05-15', departmentJoinedDate: '2018-10-10', completedDiscipleship: true },
  },
  {
    id: 'mem-4',
    fullName: 'Emmanuel Cole',
    firstName: 'Emmanuel',
    lastName: 'Cole',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    gender: 'male',
    dateOfBirth: '1998-10-07', // Upcoming in 3 days
    phoneNumber: '+1-555-0107',
    whatsAppNumber: '+15550107',
    email: 'emmanuel.cole@example.com',
    residentialAddress: '15 Apex Towers, Campus Road',
    occupation: 'Software Engineer',
    maritalStatus: 'single',
    dateJoined: '2022-01-16',
    baptismStatus: 'baptized',
    departmentId: 'dept-3',
    departmentName: 'Youth & Young Adults (Ignite)',
    cellGroup: 'Campus Ignite',
    emergencyContact: { name: 'Samuel Cole', relationship: 'Brother', phone: '+1-555-0108' },
    memberStatus: 'worker',
    notes: 'Youth leader organizing monthly evangelism drives.',
    privacy: { showPhone: true, showEmail: true, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2022-01-16', completedDiscipleship: true, departmentJoinedDate: '2022-04-10' },
  },
  {
    id: 'mem-5',
    fullName: 'Michael Sterling',
    firstName: 'Michael',
    lastName: 'Sterling',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
    gender: 'male',
    dateOfBirth: '1979-10-12', // Upcoming
    phoneNumber: '+1-555-0109',
    whatsAppNumber: '+15550109',
    email: 'michael.sterling@example.com',
    residentialAddress: '37 Cedar Crest, Hillside',
    occupation: 'Civil Engineer',
    maritalStatus: 'married',
    weddingAnniversary: '2005-04-18',
    dateJoined: '2016-06-19',
    baptismStatus: 'baptized',
    departmentId: 'dept-2',
    departmentName: 'Ushering & Protocol',
    cellGroup: 'Kingsway Cell',
    emergencyContact: { name: 'Elena Sterling', relationship: 'Spouse', phone: '+1-555-0110' },
    memberStatus: 'worker',
    notes: 'Head Usher and Security lead.',
    privacy: { showPhone: true, showEmail: true, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2016-06-19', completedDiscipleship: true, workerOrdainedDate: '2018-12-01' },
  },
  {
    id: 'mem-6',
    fullName: 'Priscilla Mensah',
    firstName: 'Priscilla',
    lastName: 'Mensah',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    gender: 'female',
    dateOfBirth: '1987-11-15',
    phoneNumber: '+1-555-0111',
    whatsAppNumber: '+15550111',
    email: 'priscilla.mensah@example.com',
    residentialAddress: '5 Willow Crescent, Lakeview',
    occupation: 'Registered Nurse',
    maritalStatus: 'married',
    weddingAnniversary: '2012-09-29',
    dateJoined: '2019-02-17',
    baptismStatus: 'baptized',
    departmentId: 'dept-6',
    departmentName: 'Welfare & Hospitality',
    cellGroup: 'Grace Sisters',
    emergencyContact: { name: 'Kofi Mensah', relationship: 'Spouse', phone: '+1-555-0112' },
    memberStatus: 'active',
    notes: 'Serves actively in health check campaigns.',
    privacy: { showPhone: true, showEmail: false, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2019-02-17', completedDiscipleship: true },
  },
  {
    id: 'mem-7',
    fullName: 'Beatrice Wilson',
    firstName: 'Beatrice',
    lastName: 'Wilson',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    gender: 'female',
    dateOfBirth: '1965-03-24',
    phoneNumber: '+1-555-0113',
    whatsAppNumber: '+15550113',
    email: 'beatrice.wilson@example.com',
    residentialAddress: '9 Garden Street, Old Quarter',
    occupation: 'Retired Headmistress',
    maritalStatus: 'widowed',
    dateJoined: '2015-05-10',
    baptismStatus: 'baptized',
    departmentId: 'dept-6',
    departmentName: 'Welfare & Hospitality',
    cellGroup: 'Wisdom Elders Cell',
    emergencyContact: { name: 'Joy Wilson', relationship: 'Daughter', phone: '+1-555-0114' },
    memberStatus: 'worker',
    notes: 'Elderly care coordinator.',
    privacy: { showPhone: true, showEmail: true, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2015-05-10', workerOrdainedDate: '2017-10-15' },
  },
  {
    id: 'mem-8',
    fullName: 'Abigail Adebayo',
    firstName: 'Abigail',
    lastName: 'Adebayo',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    gender: 'female',
    dateOfBirth: '1958-06-18',
    phoneNumber: '+1-555-0115',
    whatsAppNumber: '+15550115',
    email: 'abigail.adebayo@example.com',
    residentialAddress: '104 High Street, Sanctuary Hill',
    occupation: 'Business Consultant & Deaconess',
    maritalStatus: 'married',
    weddingAnniversary: '1981-12-20',
    dateJoined: '2015-02-01',
    baptismStatus: 'baptized',
    departmentId: 'dept-5',
    departmentName: 'Intercessory Prayer Team',
    cellGroup: 'Watchmen Prayer Circle',
    emergencyContact: { name: 'Elder Femi Adebayo', relationship: 'Husband', phone: '+1-555-0116' },
    memberStatus: 'worker',
    notes: 'Leads weekly Tuesday prayer summit.',
    privacy: { showPhone: true, showEmail: false, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2015-02-01', workerOrdainedDate: '2016-04-10' },
  },
  {
    id: 'mem-9',
    fullName: 'Jonathan Vance',
    firstName: 'Jonathan',
    lastName: 'Vance',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
    gender: 'male',
    dateOfBirth: '2001-08-14',
    phoneNumber: '+1-555-0117',
    whatsAppNumber: '+15550117',
    email: 'jonathan.vance@example.com',
    residentialAddress: '31 University Way',
    occupation: 'Undergraduate Student',
    maritalStatus: 'single',
    dateJoined: '2023-09-17',
    baptismStatus: 'baptized',
    departmentId: 'dept-3',
    departmentName: 'Youth & Young Adults (Ignite)',
    cellGroup: 'Campus Ignite',
    emergencyContact: { name: 'Deborah Vance', relationship: 'Mother', phone: '+1-555-0118' },
    memberStatus: 'active',
    notes: 'Drummer for youth services.',
    privacy: { showPhone: true, showEmail: true, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2023-09-17', baptizedDate: '2023-11-26' },
  },
  {
    id: 'mem-10',
    fullName: 'Ruth Adams',
    firstName: 'Ruth',
    lastName: 'Adams',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=200&q=80',
    gender: 'female',
    dateOfBirth: '1996-05-19',
    phoneNumber: '+1-555-0119',
    whatsAppNumber: '+15550119',
    email: 'ruth.adams@example.com',
    residentialAddress: '72 Parkside Court, Northgate',
    occupation: 'Architect',
    maritalStatus: 'single',
    dateJoined: '2020-08-23',
    baptismStatus: 'baptized',
    departmentId: 'dept-3',
    departmentName: 'Youth & Young Adults (Ignite)',
    cellGroup: 'Young Professionals Cell',
    emergencyContact: { name: 'Theresa Adams', relationship: 'Mother', phone: '+1-555-0120' },
    memberStatus: 'worker',
    notes: 'Assistant youth leader and graphic designer.',
    privacy: { showPhone: true, showEmail: true, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2020-08-23', completedDiscipleship: true },
  },
  {
    id: 'mem-11',
    fullName: 'Caleb Ofori',
    firstName: 'Caleb',
    lastName: 'Ofori',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
    gender: 'male',
    dateOfBirth: '1991-01-30',
    phoneNumber: '+1-555-0121',
    whatsAppNumber: '+15550121',
    email: 'caleb.ofori@example.com',
    residentialAddress: '14 Skyline Boulevard',
    occupation: 'Financial Analyst',
    maritalStatus: 'married',
    weddingAnniversary: '2020-02-15',
    dateJoined: '2019-11-10',
    baptismStatus: 'baptized',
    departmentId: 'dept-2',
    departmentName: 'Ushering & Protocol',
    cellGroup: 'Men of Honor',
    emergencyContact: { name: 'Naomi Ofori', relationship: 'Spouse', phone: '+1-555-0122' },
    memberStatus: 'active',
    notes: 'Helps with Sunday audit and treasury counting.',
    privacy: { showPhone: true, showEmail: true, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2019-11-10', completedDiscipleship: true },
  },
  {
    id: 'mem-12',
    fullName: 'Naomi Ofori',
    firstName: 'Naomi',
    lastName: 'Ofori',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=80',
    gender: 'female',
    dateOfBirth: '1993-04-11',
    phoneNumber: '+1-555-0123',
    whatsAppNumber: '+15550123',
    email: 'naomi.ofori@example.com',
    residentialAddress: '14 Skyline Boulevard',
    occupation: 'Pharmacist',
    maritalStatus: 'married',
    weddingAnniversary: '2020-02-15',
    dateJoined: '2020-01-05',
    baptismStatus: 'baptized',
    departmentId: 'dept-1',
    departmentName: 'Sanctuary Choir',
    cellGroup: 'Grace Sisters',
    emergencyContact: { name: 'Caleb Ofori', relationship: 'Husband', phone: '+1-555-0121' },
    memberStatus: 'active',
    notes: 'Soprano singer in choir.',
    privacy: { showPhone: true, showEmail: false, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2020-01-05', completedDiscipleship: true },
  },
  {
    id: 'mem-13',
    fullName: 'Marcus Sterling',
    firstName: 'Marcus',
    lastName: 'Sterling',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80',
    gender: 'male',
    dateOfBirth: '1985-12-03',
    phoneNumber: '+1-555-0124',
    whatsAppNumber: '+15550124',
    email: 'marcus.sterling@example.com',
    residentialAddress: '55 Pinecone Road',
    occupation: 'Logistics Supervisor',
    maritalStatus: 'single',
    dateJoined: '2017-04-12',
    baptismStatus: 'baptized',
    departmentId: 'dept-2',
    departmentName: 'Ushering & Protocol',
    cellGroup: 'Kingsway Cell',
    emergencyContact: { name: 'Michael Sterling', relationship: 'Brother', phone: '+1-555-0109' },
    memberStatus: 'inactive', // Has missed 3 recent services (Pastoral Care target)
    notes: 'Has been travelling out of state for work. Needs follow-up call.',
    privacy: { showPhone: true, showEmail: true, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2017-04-12', completedDiscipleship: true },
  },
  {
    id: 'mem-14',
    fullName: 'Hannah Taylor',
    firstName: 'Hannah',
    lastName: 'Taylor',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
    gender: 'female',
    dateOfBirth: '2004-09-22',
    phoneNumber: '+1-555-0125',
    whatsAppNumber: '+15550125',
    email: 'hannah.taylor@example.com',
    residentialAddress: '20 College Green',
    occupation: 'College Freshman',
    maritalStatus: 'single',
    dateJoined: '2024-02-11',
    baptismStatus: 'scheduled',
    departmentId: 'dept-3',
    departmentName: 'Youth & Young Adults (Ignite)',
    cellGroup: 'Campus Ignite',
    emergencyContact: { name: 'Martha Taylor', relationship: 'Mother', phone: '+1-555-0126' },
    memberStatus: 'active',
    notes: 'Signed up for upcoming water baptism class.',
    privacy: { showPhone: true, showEmail: true, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2024-02-11', completedDiscipleship: false },
  },
  {
    id: 'mem-15',
    fullName: 'Samuel Mwangi',
    firstName: 'Samuel',
    lastName: 'Mwangi',
    avatarUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=200&q=80',
    gender: 'male',
    dateOfBirth: '1974-07-09',
    phoneNumber: '+1-555-0127',
    whatsAppNumber: '+15550127',
    email: 'samuel.mwangi@example.com',
    residentialAddress: '8 Orchard Drive, East Suburbs',
    occupation: 'Real Estate Developer',
    maritalStatus: 'married',
    weddingAnniversary: '2002-08-30',
    dateJoined: '2016-10-02',
    baptismStatus: 'baptized',
    departmentId: 'dept-5',
    departmentName: 'Intercessory Prayer Team',
    cellGroup: 'Men of Honor',
    emergencyContact: { name: 'Grace Mwangi', relationship: 'Spouse', phone: '+1-555-0128' },
    memberStatus: 'worker',
    notes: 'Serves on church building maintenance committee.',
    privacy: { showPhone: true, showEmail: true, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2016-10-02', completedDiscipleship: true, workerOrdainedDate: '2019-06-12' },
  },
  {
    id: 'mem-16',
    fullName: 'Deborah Vance',
    firstName: 'Deborah',
    lastName: 'Vance',
    avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=200&q=80',
    gender: 'female',
    dateOfBirth: '1972-02-28',
    phoneNumber: '+1-555-0129',
    whatsAppNumber: '+15550129',
    email: 'deborah.vance@example.com',
    residentialAddress: '31 University Way',
    occupation: 'Senior Lecturer',
    maritalStatus: 'married',
    weddingAnniversary: '1999-07-17',
    dateJoined: '2015-08-16',
    baptismStatus: 'baptized',
    departmentId: 'dept-2',
    departmentName: 'Ushering & Protocol',
    cellGroup: 'Sanctuary Cell',
    emergencyContact: { name: 'Samuel Vance', relationship: 'Spouse', phone: '+1-555-0130' },
    memberStatus: 'worker',
    notes: 'Assistant ushering coordinator and women fellowship teacher.',
    privacy: { showPhone: true, showEmail: true, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2015-08-16', completedDiscipleship: true },
  },
  {
    id: 'mem-17',
    fullName: 'Timothy Clarke',
    firstName: 'Timothy',
    lastName: 'Clarke',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=200&q=80',
    gender: 'male',
    dateOfBirth: '1995-10-18', // Upcoming birthday in 2 weeks
    phoneNumber: '+1-555-0131',
    whatsAppNumber: '+15550131',
    email: 'timothy.clarke@example.com',
    residentialAddress: '18 Victoria Street',
    occupation: 'Photographer & Videographer',
    maritalStatus: 'single',
    dateJoined: '2023-01-22',
    baptismStatus: 'baptized',
    departmentId: 'dept-4',
    departmentName: 'Media & Communications',
    cellGroup: 'Young Professionals Cell',
    emergencyContact: { name: 'Arthur Clarke', relationship: 'Father', phone: '+1-555-0132' },
    memberStatus: 'worker',
    notes: 'Manages Sunday service livestream cameras.',
    privacy: { showPhone: true, showEmail: true, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2023-01-22', completedDiscipleship: true },
  },
  {
    id: 'mem-18',
    fullName: 'Faith Nnamdi',
    firstName: 'Faith',
    lastName: 'Nnamdi',
    avatarUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=200&q=80',
    gender: 'female',
    dateOfBirth: '2000-03-08',
    phoneNumber: '+1-555-0133',
    whatsAppNumber: '+15550133',
    email: 'faith.nnamdi@example.com',
    residentialAddress: '90 Greenfield Road',
    occupation: 'Graphic Designer',
    maritalStatus: 'single',
    dateJoined: '2022-07-10',
    baptismStatus: 'baptized',
    departmentId: 'dept-4',
    departmentName: 'Media & Communications',
    cellGroup: 'Campus Ignite',
    emergencyContact: { name: 'Kelechi Nnamdi', relationship: 'Brother', phone: '+1-555-0134' },
    memberStatus: 'active',
    notes: 'Designs sermon slide templates and announcement banners.',
    privacy: { showPhone: true, showEmail: true, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2022-07-10', completedDiscipleship: true },
  },
  {
    id: 'mem-19',
    fullName: 'Victor Balogun',
    firstName: 'Victor',
    lastName: 'Balogun',
    avatarUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=200&q=80',
    gender: 'male',
    dateOfBirth: '1989-09-14',
    phoneNumber: '+1-555-0135',
    whatsAppNumber: '+15550135',
    email: 'victor.balogun@example.com',
    residentialAddress: '43 Elmwood Terrace',
    occupation: 'Accountant',
    maritalStatus: 'married',
    weddingAnniversary: '2017-05-20',
    dateJoined: '2021-04-18',
    baptismStatus: 'baptized',
    departmentId: 'dept-2',
    departmentName: 'Ushering & Protocol',
    cellGroup: 'Kingsway Cell',
    emergencyContact: { name: 'Ronke Balogun', relationship: 'Spouse', phone: '+1-555-0136' },
    memberStatus: 'active',
    notes: 'Auditor for welfare disbursements.',
    privacy: { showPhone: true, showEmail: true, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2021-04-18', completedDiscipleship: true },
  },
  {
    id: 'mem-20',
    fullName: 'Chloe Davies',
    firstName: 'Chloe',
    lastName: 'Davies',
    avatarUrl: 'https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=200&q=80',
    gender: 'female',
    dateOfBirth: '2002-11-04',
    phoneNumber: '+1-555-0137',
    whatsAppNumber: '+15550137',
    email: 'chloe.davies@example.com',
    residentialAddress: '7 St. Andrews Court',
    occupation: 'Medical Intern',
    maritalStatus: 'single',
    dateJoined: '2024-08-04',
    baptismStatus: 'scheduled',
    departmentId: 'dept-1',
    departmentName: 'Sanctuary Choir',
    cellGroup: 'Youth & Young Adults (Ignite)',
    emergencyContact: { name: 'Julian Davies', relationship: 'Father', phone: '+1-555-0138' },
    memberStatus: 'visitor', // New Convert / Visitor
    notes: 'First visited during August praise festival. Joined foundations class.',
    privacy: { showPhone: true, showEmail: true, showBirthday: true, showAddress: false, showPhoto: true },
    journey: { dateJoined: '2024-08-04', completedDiscipleship: false },
  },
];

export const INITIAL_EVENTS: ChurchEvent[] = [
  {
    id: 'evt-1',
    title: 'Sunday Celebration & Communion Service',
    description: 'An unforgettable encounter in worship, practical word of faith, and Holy Communion. Bring your family and friends!',
    category: 'sunday_service',
    date: '2026-10-05', // Tomorrow!
    startTime: '09:00',
    endTime: '11:30',
    location: 'Main Sanctuary & Livestream Online',
    speaker: 'Pastor David Adeleke',
    posterUrl: 'https://images.unsplash.com/photo-1438232992991-995b7058bbb3?auto=format&fit=crop&w=800&q=80',
    registrationRequired: false,
    targetAudience: 'All Members, Guests & Online Family',
    registeredCount: 380,
    remindersSent: ['7d', '3d'],
  },
  {
    id: 'evt-2',
    title: 'Midweek Bible Exposition: Walking in the Spirit',
    description: 'Verse-by-verse exposition of Galatians Chapter 5. Interactive Q&A and table discussions.',
    category: 'bible_study',
    date: '2026-10-07', // In 3 days!
    startTime: '18:30',
    endTime: '20:00',
    location: 'Sanctuary Hall B & Zoom',
    speaker: 'Pastor David Adeleke',
    posterUrl: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?auto=format&fit=crop&w=800&q=80',
    registrationRequired: false,
    targetAudience: 'Workers, Students & Seekers',
    registeredCount: 145,
    remindersSent: ['7d'],
  },
  {
    id: 'evt-3',
    title: 'Ignite Youth Breakthrough Summit 2026',
    description: 'Igniting purpose, digital leadership, and spiritual depth in young professionals and campus students.',
    category: 'youth',
    date: '2026-10-10',
    startTime: '14:00',
    endTime: '19:00',
    location: 'Grace Youth Center',
    speaker: 'Minister Emmanuel Cole & Guest Panellists',
    posterUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
    registrationRequired: true,
    targetAudience: 'Ages 16 – 35',
    registeredCount: 88,
    remindersSent: [],
  },
  {
    id: 'evt-4',
    title: 'Monthly Night of Supernatural Wonders & Healing',
    description: 'Intense intercession, prophetic ministration, healing, and breakthroughs for families.',
    category: 'revival',
    date: '2026-10-16',
    startTime: '22:00',
    endTime: '04:00',
    location: 'Main Sanctuary',
    speaker: 'Pastor David Adeleke & Pastoral Team',
    posterUrl: 'https://images.unsplash.com/photo-1478147427282-58a87a120781?auto=format&fit=crop&w=800&q=80',
    registrationRequired: false,
    targetAudience: 'General Congregation',
    registeredCount: 220,
    remindersSent: [],
  },
  {
    id: 'evt-5',
    title: 'Marriage & Family Enrichment Banquet',
    description: 'An elegant dinner evening for married and engaged couples discussing communication, finances, and lasting intimacy.',
    category: 'special',
    date: '2026-10-24',
    startTime: '17:00',
    endTime: '21:00',
    location: 'Grand Ballroom, Royal Palm Hotel',
    speaker: 'Pastor David & Mary Adeleke',
    posterUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
    registrationRequired: true,
    targetAudience: 'Married & Engaged Couples',
    registeredCount: 42,
    remindersSent: [],
  },
];

export const INITIAL_DEVOTIONALS: Devotional[] = [
  {
    id: 'dev-today',
    date: '2026-10-04',
    title: 'Anchored in Unshakable Trust',
    bibleVerse: 'Trust in the Lord with all your heart, and lean not on your own understanding; in all your ways acknowledge Him, and He shall direct your paths.',
    bibleReference: 'Proverbs 3:5-6 (NKJV)',
    content: 'Life often presents seasons where the road ahead seems foggy and human logic fails. It is in such moments that trust becomes our greatest anchor. God does not ask you to figure out every step before you move; He asks you to place your hand in His. True faith is resting in the character of the God who has never once failed. When you acknowledge Him in your career decisions, your family worries, and your private silent battles, He makes your path straight and clears obstacles you never knew were there.',
    prayer: 'Heavenly Father, I surrender my anxieties and calculated schemes to Your loving wisdom. Teach my heart to rest completely in Your unfailing faithfulness. Lead my footsteps today, in Jesus name. Amen.',
    reflectionQuestion: 'In what area of your life this week have you been leaning on your own understanding rather than inviting God in?',
    author: 'Pastor David Adeleke',
    likes: 84,
  },
  {
    id: 'dev-yesterday',
    date: '2026-10-03',
    title: 'The Peace That Transcends Circumstances',
    bibleVerse: 'Peace I leave with you, My peace I give to you; not as the world gives do I give to you. Let not your heart be troubled, neither let it be afraid.',
    bibleReference: 'John 14:27 (NKJV)',
    content: 'Worldly peace depends on favourable bank accounts, smooth relationships, and good health. But the peace Jesus offers is an internal fortress constructed by His abiding Presence. Even when storms rage on the outside, His peace anchors the soul within.',
    prayer: 'Lord Jesus, impart Your supernatural calmness into my spirit today. Guard my mind from fear and anxious thoughts. Amen.',
    reflectionQuestion: 'Where are you currently looking for peace that only Christ can provide?',
    author: 'Pastor David Adeleke',
    likes: 67,
  },
];

export const INITIAL_SERMONS: Sermon[] = [
  {
    id: 'sermon-1',
    title: 'Unlocking Greater Realms of Faith',
    speaker: 'Pastor David Adeleke',
    date: '2026-09-28',
    category: 'Faith',
    description: 'Learn how simple obedience unleashes supernatural provision, breaks persistent barriers, and elevates your Christian walk into divine confidence.',
    bibleReferences: ['Hebrews 11:1-6', 'Mark 11:22-24', 'Romans 10:17'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?auto=format&fit=crop&w=600&q=80',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    pdfUrl: '/sermons/unlocking-greater-realms-of-faith.pdf',
    duration: '48 mins',
    summary: 'Faith is not positive thinking; it is acting on God\'s unchanging Word. When we align our speech, our actions, and our expectations with Scripture, God moves decisively on our behalf.',
    discussionQuestions: [
      'What is the difference between mental agreement and biblical faith?',
      'How does hearing the Word continuously transform our prayer life?',
      'Share a testimony where God answered a bold step of faith in your life.'
    ],
    prayerPoints: [
      'Lord, eradicate every root of unbelief and hesitation in my heart.',
      'Father, give me courage to step onto the water when You bid me come.',
      'Holy Spirit, enlarge my spiritual capacity to believe You for great things.'
    ],
  },
  {
    id: 'sermon-2',
    title: 'The Secret Place of Intimacy and Power',
    speaker: 'Pastor David Adeleke',
    date: '2026-09-21',
    category: 'Prayer',
    description: 'Discovering the joy of daily communion with God in the secret place, where true spiritual strength and clarity are birthed.',
    bibleReferences: ['Psalm 91:1-4', 'Matthew 6:6', 'James 4:8'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1544427920-c49ccfb85579?auto=format&fit=crop&w=600&q=80',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    pdfUrl: '/sermons/the-secret-place.pdf',
    duration: '52 mins',
    summary: 'Public victory is forged in private devotion. When you cultivate quiet moments to hear His voice, you walk in an unshakable mantle of divine peace.',
    discussionQuestions: [
      'What are the common distractions that hinder our consistency in the secret place?',
      'How can we transition from praying through a shopping list to relational communion?'
    ],
    prayerPoints: [
      'Father, restore in me a holy hunger for Your daily presence.',
      'Silence every worldly noise competing with Your gentle whisper.'
    ],
  },
  {
    id: 'sermon-3',
    title: 'Building Strong Christian Families in Modern Times',
    speaker: 'Elder Samuel & Deborah Vance',
    date: '2026-09-14',
    category: 'Family',
    description: 'Biblical wisdom on nurturing love, honour, mutual respect, and intentional parenting amidst societal pressures.',
    bibleReferences: ['Ephesians 5:21-33', 'Joshua 24:15', 'Proverbs 22:6'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=600&q=80',
    duration: '45 mins',
    summary: 'A Christ-centered home is a fortress of peace. We must intentionally build altars of prayer, honest communication, and forgiveness within our family life.',
  },
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-1',
    title: 'The Church — Discipleship Foundations Manual (PDF)',
    category: 'Church Manual',
    fileType: 'pdf',
    fileSize: '2.4 MB',
    uploadedDate: '2026-08-15',
    downloadCount: 312,
    description: 'A comprehensive 6-week curriculum for new converts and growing believers on Salvation, Holy Spirit, Prayer, Giving, and Ministry.',
    contentSnippet: 'Chapter 1: The Assurance of Salvation — Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new (2 Corinthians 5:17). Salvation is not earned by moral deeds...',
  },
  {
    id: 'doc-2',
    title: 'Sermon Study Notes: Galatians Verse-by-Verse Guide',
    category: 'Bible Study',
    fileType: 'pdf',
    fileSize: '1.1 MB',
    uploadedDate: '2026-09-20',
    downloadCount: 189,
    description: 'Accompanying study outline and Greek word commentary for Wednesday evening Midweek classes.',
    contentSnippet: 'Galatians 5:1 — Stand fast therefore in the liberty wherewith Christ hath made us free... The Greek word for liberty is eleutheria, denoting not lawlessness, but genuine emancipation from religious bondage...',
  },
  {
    id: 'doc-3',
    title: '21 Days of Fasting & Prayer Breakthrough Guide 2026',
    category: 'Prayer Guide',
    fileType: 'pdf',
    fileSize: '890 KB',
    uploadedDate: '2026-09-01',
    downloadCount: 420,
    description: 'Daily scriptural prayer points, fasting tips, and prophetic declarations for spiritual alignment.',
    contentSnippet: 'Day 1: Consecration & Personal Cleansing (Psalm 51). Day 2: Divine Direction & Open Doors (Isaiah 30:21). Day 3: Supernatural Health & Healing (3 John 1:2)...',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Sunday Celebration Service Times & Shuttle Bus Pickup',
    content: 'Beloved church family, our Sunday celebration service kicks off at 09:00 AM prompt. Complimentary church shuttle buses will depart Central Station at 08:15 AM and 08:45 AM. Children\'s church classes will run concurrently in Hall C.',
    category: 'general',
    publishedDate: '2026-10-03',
    isPinned: true,
    author: 'Secretariat',
    readCount: 342,
  },
  {
    id: 'ann-2',
    title: 'Water Baptism Class for New Converts & Believers',
    content: 'Are you ready to make a public declaration of your faith in Christ? The next water baptismal immersion service is scheduled for Saturday, October 24 at 10:00 AM. Please register at the protocol desk or via the member portal.',
    category: 'urgent',
    publishedDate: '2026-10-01',
    isPinned: true,
    author: 'Pastor David Adeleke',
    readCount: 280,
  },
  {
    id: 'ann-3',
    title: 'Youth Choir Auditions — Join the Ignite Music Ministry',
    content: 'The Sanctuary Choir & Youth Worship band are holding open auditions for vocalists (soprano, alto, tenor) and instrumentalists (keyboard, bass, electric guitar). Rehearsals are Thursdays at 6 PM.',
    category: 'department',
    departmentName: 'Sanctuary Choir',
    publishedDate: '2026-09-29',
    isPinned: false,
    author: 'Grace Okafor (Choir Director)',
    readCount: 195,
  },
];

export const INITIAL_PRAYER_REQUESTS: PrayerRequest[] = [
  {
    id: 'pr-1',
    memberName: 'Priscilla Mensah',
    memberId: 'mem-6',
    contactPhone: '+1-555-0111',
    requestText: 'Please pray for my mother\'s upcoming knee surgery on Wednesday morning. Pray for guidance for the surgeon and swift recovery without complications.',
    category: 'Healing',
    urgency: 'high',
    isAnonymous: false,
    status: 'being_prayed_for',
    submittedAt: '2026-10-02T14:30:00Z',
    pastoralNotes: 'Intercessory team notified. Sent pastoral audio prayer.',
  },
  {
    id: 'pr-2',
    memberName: 'Anonymous Sister',
    requestText: 'Seeking God\'s divine wisdom and open doors for a major job promotion interview this Friday. Pray that favour surrounds me like a shield.',
    category: 'Finance',
    urgency: 'medium',
    isAnonymous: true,
    status: 'new',
    submittedAt: '2026-10-03T18:45:00Z',
  },
  {
    id: 'pr-3',
    memberName: 'Emmanuel Cole',
    memberId: 'mem-4',
    contactPhone: '+1-555-0107',
    requestText: 'Thanksgiving! The Lord granted our startup funding approval and we are dedicating the business to God\'s kingdom expansion.',
    category: 'Thanksgiving',
    urgency: 'low',
    isAnonymous: false,
    status: 'resolved',
    submittedAt: '2026-09-28T09:15:00Z',
    pastoralNotes: 'Announced testimony during Sunday service.',
  },
  {
    id: 'pr-4',
    memberName: 'Marcus Sterling',
    memberId: 'mem-13',
    contactPhone: '+1-555-0124',
    requestText: 'Struggling with fatigue, spiritual dryness, and work travel exhaustion. Seeking renewed strength from the Holy Spirit.',
    category: 'Spiritual Growth',
    urgency: 'medium',
    isAnonymous: false,
    status: 'follow_up_required',
    submittedAt: '2026-10-01T20:10:00Z',
    pastoralNotes: 'Assigned to Elder Vance for pastoral call.',
  },
];

export const INITIAL_FOLLOW_UPS: PastoralFollowUp[] = [
  {
    id: 'fu-1',
    memberId: 'mem-13',
    memberName: 'Marcus Sterling',
    memberPhone: '+1-555-0124',
    type: 'absent_member',
    assignedToName: 'Michael Sterling',
    assignedToEmail: 'michael.sterling@example.com',
    status: 'in_progress',
    scheduledDate: '2026-10-04',
    notes: 'Marcus has missed the last 3 Sunday services due to out-of-town consulting projects. Reached out with warm pastoral greeting on WhatsApp.',
    outcome: 'Responded warmly. Confirmed he will join tomorrow\'s service in person.',
  },
  {
    id: 'fu-2',
    memberId: 'mem-20',
    memberName: 'Chloe Davies',
    memberPhone: '+1-555-0137',
    type: 'new_member',
    assignedToName: 'Sarah Jenkins',
    assignedToEmail: 'sarah.jenkins@example.com',
    status: 'pending',
    scheduledDate: '2026-10-05',
    notes: 'New convert from campus outreach. Send welcome packet and invite to Ignite youth fellowship on Saturday.',
  },
  {
    id: 'fu-3',
    memberId: 'mem-7',
    memberName: 'Beatrice Wilson',
    memberPhone: '+1-555-0113',
    type: 'hospital_visit',
    assignedToName: 'Abigail Adebayo',
    assignedToEmail: 'abigail.adebayo@example.com',
    status: 'completed',
    scheduledDate: '2026-09-29',
    notes: 'Routine elder visit and communion distribution at home.',
    outcome: 'Wonderful prayer time. Sister Beatrice is in high spirits and joyful.',
  },
];

export const INITIAL_WHATSAPP_CONFIG: WhatsAppConfig = {
  phoneNumberId: '',
  wabaId: '',
  accessToken: '',
  verifiedNumber: '+1 (555) 728-4673',
  businessName: 'The Church Official',
  isConnected: false, // Transparent architecture: not configured until credentials entered
  approvalMode: 'manual', // Manual approval by Pastor David Adeleke by default (Safety First)
  autoBirthdayEnabled: true,
  autoVisitorWelcomeEnabled: true,
  autoEventReminderEnabled: true,
};

export const INITIAL_WHATSAPP_TEMPLATES: WhatsAppTemplate[] = [
  {
    id: 'tpl-1',
    name: 'pastoral_birthday_blessing',
    category: 'MARKETING',
    language: 'en_US',
    status: 'APPROVED',
    body: 'Happy Birthday, {{1}}! 🎉🎂 The Church celebrates you today. May the Lord shine His countenance upon you, grant you good health, and establish the desires of your heart in this new season. God bless you richly! — {{2}}',
    exampleVariables: ['John', 'Pastor David Adeleke'],
  },
  {
    id: 'tpl-2',
    name: 'event_reminder_broadcast',
    category: 'UTILITY',
    language: 'en_US',
    status: 'APPROVED',
    body: 'Hello {{1}}, reminder: Our {{2}} takes place on {{3}} at {{4}}. Location: {{5}}. We look forward to fellowship with you! Come expectant.',
    exampleVariables: ['Sarah', 'Sunday Celebration Service', 'Tomorrow', '09:00 AM', 'Main Sanctuary'],
  },
  {
    id: 'tpl-3',
    name: 'new_visitor_welcome',
    category: 'MARKETING',
    language: 'en_US',
    status: 'APPROVED',
    body: 'Hello {{1}}! We were deeply blessed to have you worship with us at The Church today. May your week be filled with divine peace and favour. If you need prayer or have questions, feel free to reply directly to this message. Blessings!',
    exampleVariables: ['David'],
  },
  {
    id: 'tpl-4',
    name: 'absent_member_caring_checkin',
    category: 'MARKETING',
    language: 'en_US',
    status: 'APPROVED',
    body: 'Dear {{1}}, we missed your warm presence at {{2}} this weekend! We are praying for God\'s peace and strength over you and your home. Please let us know if there is anything we can stand in agreement with you in prayer for. — {{3}}',
    exampleVariables: ['Brother Marcus', 'Sunday Service', 'Pastor David Adeleke'],
  },
];

export const INITIAL_WHATSAPP_MESSAGES: WhatsAppMessage[] = [
  {
    id: 'msg-1',
    recipientName: 'David Adeleke',
    recipientPhone: '+15550101',
    memberId: 'mem-1',
    messageType: 'birthday',
    messageText: 'Happy Birthday, Pastor David! 🎉 On behalf of The Church, we thank God for your selfless leadership and shepherd\'s heart. May the anointing upon you multiply abundantly!',
    status: 'delivered',
    timestamp: '2026-10-04T07:15:00Z',
  },
  {
    id: 'msg-2',
    recipientName: 'Sarah Jenkins',
    recipientPhone: '+15550103',
    memberId: 'mem-2',
    messageType: 'birthday',
    messageText: 'Happy Birthday, Sarah! 🎂 The Lord bless you abundantly and reward your dedication to the media ministry. May this new year bring joy and divine elevation!',
    status: 'read',
    timestamp: '2026-10-04T07:16:00Z',
  },
  {
    id: 'msg-3',
    recipientName: 'Grace Okafor',
    recipientPhone: '+15550105',
    memberId: 'mem-3',
    messageType: 'birthday',
    messageText: 'Happy Birthday, Grace! 🎈 May the Lord fill your life with sweet melodies of joy and victory. Thank you for lifting our spirits every Sunday!',
    status: 'delivered',
    timestamp: '2026-10-04T07:16:30Z',
  },
  {
    id: 'msg-4',
    recipientName: 'Marcus Sterling',
    recipientPhone: '+15550124',
    memberId: 'mem-13',
    messageType: 'absent_checkin',
    messageText: 'Dear Marcus, we missed your presence at church this Sunday! Praying for God\'s supernatural strength over your work travels. See you soon!',
    status: 'read',
    timestamp: '2026-10-03T16:00:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    userName: 'Pastor David Adeleke',
    action: 'Birthday Greetings Prepared',
    details: 'Prepared 3 AI birthday messages for Oct 4 celebrants.',
    timestamp: '2026-10-04T07:12:00Z',
  },
  {
    id: 'log-2',
    userName: 'Secretariat Admin',
    action: 'Announcement Published',
    details: 'Published Sunday shuttle and service details announcement.',
    timestamp: '2026-10-03T11:45:00Z',
  },
  {
    id: 'log-3',
    userName: 'Pastor David Adeleke',
    action: 'Sermon Uploaded',
    details: 'Uploaded audio sermon and discussion notes for "Unlocking Greater Realms of Faith".',
    timestamp: '2026-09-28T14:20:00Z',
  },
  {
    id: 'log-4',
    userName: 'Membership Secretary',
    action: 'New Member Registered',
    details: 'Registered Chloe Davies into Youth department.',
    timestamp: '2026-08-04T12:00:00Z',
  },
];

export const INITIAL_GALLERY: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'Worship Encounter — Sunday Celebration',
    event: 'Sunday Service',
    date: '2026-09-28',
    category: 'Sunday Service',
    imageUrl: 'https://images.unsplash.com/photo-1438232992991-995b7058bbb3?auto=format&fit=crop&w=800&q=80',
    caption: 'Deep moment of worship led by the Sanctuary choir during Sunday morning service.',
  },
  {
    id: 'gal-2',
    title: 'Water Baptismal Immersion',
    event: 'Quarterly Baptism',
    date: '2026-08-20',
    category: 'Baptism',
    imageUrl: 'https://images.unsplash.com/photo-1544427920-c49ccfb85579?auto=format&fit=crop&w=800&q=80',
    caption: '14 souls made public declarations of faith in Christ Jesus.',
  },
  {
    id: 'gal-3',
    title: 'Community Food Bank & Welfare Outreach',
    event: 'Welfare Outreach',
    date: '2026-09-12',
    category: 'Outreach',
    imageUrl: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80',
    caption: 'Distributing over 200 grocery packages to families in need in our neighbourhood.',
  },
  {
    id: 'gal-4',
    title: 'Ignite Youth Worship Night',
    event: 'Youth Ministry',
    date: '2026-09-19',
    category: 'Youth',
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
    caption: 'Young believers passionate about spiritual awakening and purposeful living.',
  },
];

export const INITIAL_READING_PLANS: ReadingPlan[] = [
  {
    id: 'plan-1',
    title: '30-Day Gospel Journey (Life of Christ)',
    durationDays: 30,
    description: 'Walk step-by-step through the miracles, parables, death, and resurrection of Jesus across Matthew, Mark, Luke, and John.',
    currentDay: 4,
    totalDays: 30,
    completedDays: [1, 2, 3],
  },
  {
    id: 'plan-2',
    title: '90-Day New Testament Challenge',
    durationDays: 90,
    description: 'A structured daily chapter-by-chapter reading plan through Acts, the Epistles, and Revelation.',
    currentDay: 1,
    totalDays: 90,
    completedDays: [],
  },
  {
    id: 'plan-3',
    title: 'Proverbs: 31 Days of Wisdom',
    durationDays: 31,
    description: 'Read one chapter of Proverbs corresponding to each day of the month for practical divine wisdom in finance, speech, and relationships.',
    currentDay: 4,
    totalDays: 31,
    completedDays: [1, 2, 3, 4],
  },
];

export const BIBLE_VERSES_DATABASE: BibleVerseItem[] = [
  { book: 'Proverbs', chapter: 3, verse: 5, text: 'Trust in the Lord with all thine heart; and lean not unto thine own understanding.', translation: 'KJV', topic: 'Faith & Trust' },
  { book: 'Proverbs', chapter: 3, verse: 6, text: 'In all thy ways acknowledge him, and he shall direct thy paths.', translation: 'KJV', topic: 'Guidance' },
  { book: 'Philippians', chapter: 4, verse: 6, text: 'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.', translation: 'KJV', topic: 'Peace & Anxiety' },
  { book: 'Philippians', chapter: 4, verse: 7, text: 'And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.', translation: 'KJV', topic: 'Peace' },
  { book: 'Philippians', chapter: 4, verse: 13, text: 'I can do all things through Christ which strengtheneth me.', translation: 'KJV', topic: 'Strength' },
  { book: 'Jeremiah', chapter: 29, verse: 11, text: 'For I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil, to give you an expected end.', translation: 'KJV', topic: 'Hope & Future' },
  { book: 'Isaiah', chapter: 40, verse: 31, text: 'But they that wait upon the Lord shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.', translation: 'KJV', topic: 'Renewal & Strength' },
  { book: 'Romans', chapter: 8, verse: 28, text: 'And we know that all things work together for good to them that love God, to them who are the called according to his purpose.', translation: 'KJV', topic: 'Purpose & Providence' },
  { book: 'Psalm', chapter: 23, verse: 1, text: 'The Lord is my shepherd; I shall not want.', translation: 'KJV', topic: 'Provision & Comfort' },
  { book: 'Psalm', chapter: 91, verse: 1, text: 'He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.', translation: 'KJV', topic: 'Protection' },
  { book: 'Psalm', chapter: 119, verse: 105, text: 'Thy word is a lamp unto my feet, and a light unto my path.', translation: 'KJV', topic: 'God\'s Word' },
  { book: 'Matthew', chapter: 6, verse: 33, text: 'But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.', translation: 'KJV', topic: 'Kingdom Priority' },
  { book: 'Matthew', chapter: 11, verse: 28, text: 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.', translation: 'KJV', topic: 'Rest' },
  { book: 'John', chapter: 14, verse: 6, text: 'Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.', translation: 'KJV', topic: 'Salvation' },
  { book: 'Hebrews', chapter: 11, verse: 1, text: 'Now faith is the substance of things hoped for, the evidence of things not seen.', translation: 'KJV', topic: 'Faith' },
  { book: 'Hebrews', chapter: 11, verse: 6, text: 'But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him.', translation: 'KJV', topic: 'Faith & Seeking God' },
  { book: '1 Corinthians', chapter: 13, verse: 13, text: 'And now abideth faith, hope, charity, these three; but the greatest of these is charity.', translation: 'KJV', topic: 'Love' },
  { book: '2 Timothy', chapter: 1, verse: 7, text: 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.', translation: 'KJV', topic: 'Courage & Mind' },
];
